Create landing boilerplate with prepared dependencies

diff --git a/doc-site-generator/Makefile b/doc-site-generator/Makefile
--- a/doc-site-generator/Makefile
+++ b/doc-site-generator/Makefile
@@ -1,6 +1,3 @@
-# Assign any value in case you want to commit every step of the generation
-WITH_COMMIT ?=
-
 # provided by ci.docs
 export HOST_NAME ?=
 export BASE_URL ?=
@@ -9,7 +6,8 @@ OUTPUT ?=
 SOURCES ?=
 
 # config
-landing := $(shell pwd)
+landing ?= $(shell pwd)
+boilerplate := $(landing)/../landing.boilerplate
 project_yml_generator := $(landing)/doc-site-generator/src/*.go
 src_assets := $(landing)/doc-site-generator/assets
 src_categories_yml := $(landing)/hugo/data/categories.yml
@@ -18,39 +16,27 @@ src_landing_hugo := $(src_assets)/site
 output_raw := $(OUTPUT)/hugo/content/raw
 output_yml := $(OUTPUT)/hugo/data/project.yml
 
-# functions
-define git-init =
-	$(REMOVE) $(OUTPUT)/.git; \
-	if [ -n "$(WITH_COMMIT)" ]; then \
-		cd $(OUTPUT); \
-		git init; \
-	fi;
-endef
-define git-commit =
-	if [ -n "$(WITH_COMMIT)" ]; then \
-		cd $(OUTPUT); \
-		git add -A; \
-		git commit -m $(1); \
-	fi;
-endef
+ifdef SOURCES
+  output_tmp = $(SOURCES)/.doc-site-sources-$(VERSION)
+else
+  output_tmp = $(boilerplate)/.doc-site-sources
+endif
 
+# Creates a landing-like project into the OUTPUT directory
+prepare-landing-like: copy-landing copy-assets clean-landing
 
-## Generate documentation site
-generate-documentation-site: copy-landing clean-landing import-documentation
-
-# Creates a new landing-like project based in the current one
-copy-landing: prepare-output
-	$(COPY) $(landing) $(OUTPUT)
-	$(git-init)
-	$(call git-commit,"Create Landing copy")
-
-# Deletes target if already existent
-prepare-output:
+# Copies the current landing into a cleaned OUTPUT directory
+copy-landing:
 ifndef OUTPUT
 	$(error "error 'OUTPUT' can not be null.")
 endif
 	$(MKDIR) $(OUTPUT)
 	$(REMOVE) $(OUTPUT)
+	$(COPY) $(landing) $(OUTPUT)
+
+# Copies documentation assets into the OUTPUT directory
+copy-assets:
+	$(COPY) $(src_landing_hugo)/* $(OUTPUT);
 
 # Clean files from Landing
 sections_to_clean := home careers manifesto projects stack team temporal upcoming
@@ -63,46 +49,76 @@ clean-landing:
 		$(REMOVE) $(OUTPUT)/hugo/data/$${section}; \
 		$(REMOVE) $(OUTPUT)/hugo/data/$${section}.yml; \
 	done;
-	@$(REMOVE) $(OUTPUT)/Makefile.doc;
-	@$(REMOVE) $(OUTPUT)/doc-site-generator;
-	$(call git-commit,"Clean project")
 
 # Import documentation from an external project
 import-documentation:
-	$(COPY) $(src_landing_hugo)/* $(OUTPUT)
-
+ifdef SOURCES
 	$(COPY) $(SOURCES)/README.md $(output_raw)
 
 	$(COPY) $(SOURCES)/LICENSE $(output_raw)
 
-	@if [ -d $(SOURCES)/_tutorials ]; then \
+	@if [[ -d $(SOURCES)/_tutorials ]]; then \
 		$(COPY) $(SOURCES)/_tutorials/* $(output_raw)/documentation/tutorials/; \
 	fi;
 
-	@if [ -d $(SOURCES)/_examples ]; then \
+	@if [[ -d $(SOURCES)/_examples ]]; then \
 		$(COPY) $(SOURCES)/_examples/* $(output_raw)/documentation/examples/; \
 	fi;
 
 	go run $(project_yml_generator) -tpl=$(src_project_tpl) -readme=$(SOURCES)/README.md -categories=$(src_categories_yml) > $(output_yml)
 
-	$(call git-commit,"Import content from sources")
+	$(REMOVE) $(OUTPUT)/doc-site-generator;
+endif
+
+## Creates a boilerplate containing all landing-like dependencies
+boilerplate-prepare:
+	$(MAKE) -C $(landing) prepare-landing-like OUTPUT=$(boilerplate)
+	$(MAKE) -C $(boilerplate) project-dependencies
+	$(REMOVE) \
+		$(boilerplate)/package.json \
+		$(boilerplate)/webpack.config.js \
+		$(boilerplate)/src \
+		$(boilerplate)/node_modules;
+
+## Generate a documentation site from the boilerplate
+boilerplate-compile:
+	@if [[ ! -d "$(boilerplate)" ]]; then \
+		echo "error No boilerplate already created at '$(boilerplate)'."; \
+		exit 1; \
+	fi;
+
+	$(MAKE) -C $(boilerplate) copy-landing OUTPUT=$(output_tmp)
+
+	$(MAKE) -C $(output_tmp) import-documentation OUTPUT=$(output_tmp)
+
+	$(MAKE) -C $(output_tmp) hugo-build DESTINATION=$(output_tmp)/public
+
+	$(MKDIR) $(OUTPUT)
+	$(MOVE) $(output_tmp)/public/* $(OUTPUT)
+	$(REMOVE) $(output_tmp)
+
+## Generate a documentation site
+generate-documentation-site: prepare-landing-like import-documentation
+	$(MAKE) -C $(OUTPUT) serve;
 
 
-# Develop vars
+# ----------
+
+# Develop. vars
 dev_output_project_yml := $(landing)/hugo/data/project.yml
 dev_src_raw := $(src_assets)/examples/hugo/content/raw
 dev_output_raw := $(landing)/hugo/content/raw
 dev_src_doc:=$(src_assets)/site/hugo/content
 dev_output_doc := $(landing)/hugo/content/documentation
 
-# Develop documentation over current landing
+## Develop. Prepares the current Landing to look like a documentation site
 develop-documentation:
 	$(MKDIR) $(dev_output_doc)
 	$(COPY) $(dev_src_raw) $(dev_output_raw)
 	$(COPY) $(dev_src_doc)/*.md $(dev_output_doc)
 	go run $(project_yml_generator) -tpl=$(src_project_tpl) -readme=$(SOURCES)/README.md -categories=$(src_categories_yml) > $(dev_output_project_yml)
 
-# Remove develop documentation
+## Develop. Remove all stuff created to look like a documentation site
 develop-documentation-destroy:
 	$(REMOVE) $(dev_output_raw)
 	$(REMOVE) $(dev_output_doc)
